use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Participant {
    pub participant_id: i64,
    pub team_id: i64,
    pub win: bool,
    pub champion_id: i64,
    pub champion_name: String,
    pub summoner_name: String,
    pub profile_icon_id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub puuid: Option<String>,
    pub kills: i64,
    pub deaths: i64,
    pub assists: i64,
    pub gold_earned: i64,
    pub total_minions_killed: i64,
    pub neutral_minions_killed: i64,
    pub vision_wards_bought_in_game: i64,
    pub vision_score: i64,
    pub wards_placed: i64,
    pub wards_killed: i64,
    pub damage_dealt_to_champions: i64,
    pub damage_taken: i64,
    pub total_heal: i64,
    pub time_played: i64,
    pub item0: i64,
    pub item1: i64,
    pub item2: i64,
    pub item3: i64,
    pub item4: i64,
    pub item5: i64,
    pub item6: i64,
    pub champion_level: i64,
    pub summoner1_id: i64,
    pub summoner2_id: i64,
    pub perk0: i64,
    pub perk1: i64,
    pub perk2: i64,
    pub perk3: i64,
    pub perk4: i64,
    pub perk5: i64,
    pub perk_primary_style: i64,
    pub perk_sub_style: i64,
    pub champ_level: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Match {
    pub game_id: String,
    pub game_creation: i64,
    pub game_duration: i64,
    pub game_mode: String,
    pub game_type: String,
    pub game_version: String,
    pub map_id: i64,
    pub queue_id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub participant_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub team_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub win: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub champion_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub champion_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kills: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deaths: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assists: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gold_earned: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_minions_killed: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub neutral_minions_killed: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vision_wards_bought_in_game: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vision_score: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wards_placed: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wards_killed: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub damage_dealt_to_champions: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub damage_taken: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_heal: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_played: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item0: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item1: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item2: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item3: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item4: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item5: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item6: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub champion_level: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summoner1_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summoner2_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub perk0: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub perk1: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub perk2: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub perk3: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub perk4: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub perk5: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub perk_primary_style: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub perk_sub_style: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub participants: Option<Vec<Participant>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MatchDetail {
    pub game_id: String,
    pub game_creation: i64,
    pub game_duration: i64,
    pub game_mode: String,
    pub game_type: String,
    pub game_version: String,
    pub map_id: i64,
    pub queue_id: i64,
    pub participants: Vec<Participant>,
}
